name: Deploy
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy'
        default: 'env'
        required: true
        type: choice
        options:
          - 'env'
          - 'sftp'
          - 'ftps'
jobs:
  bulid:
    name: Build
    runs-on: ubuntu-latest
    env:
      UNITY_BUILD_PATH: build/WebGL/WebGL/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Make build directory
        run: mkdir ${{ env.UNITY_BUILD_PATH }}

      - name: Setup Unity Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.4f1

      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ${{ env.UNITY_BUILD_PATH }}

      - name: Deploy by SFTP
        if: ${{ inputs.deploy == 'sftp' || inputs.deploy == 'env' && vars.DEPLOY_PROTOCOL == 'sftp' }}
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SFTP_HOST }}
          remote-user: ${{ secrets.SFTP_USER }}
          private-ssh-key: ${{ secrets.SFTP_KEY }}
          ssh-port: ${{ secrets.SFTP_PORT }}
          source-path: ${{ env.UNITY_BUILD_PATH }}
          destination-path: ${{ secrets.SFTP_DEST_PATH }}

      - name: Deploy by FTPS
        if: ${{ inputs.deploy == 'ftps' || inputs.deploy == 'env' && vars.DEPLOY_PROTOCOL == 'ftps' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTPS_HOST }}
          username: ${{ secrets.FTPS_USER }}
          password: ${{ secrets.FTPS_PASSWORD }}
          port: ${{ secrets.FTPS_PORT }}
          protocol: ftps
          local-dir: ${{ env.UNITY_BUILD_PATH }}
          server-dir: ${{ secrets.FTPS_DEST_PATH }}
