name: deploy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Unity Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.4f1

      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

      - name: Deploy
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SERVER_HOST }}
          remote-user: ${{ secrets.SERVER_USER }}
          private-ssh-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-port: ${{ secrets.SERVER_PORT }}
          source-path: ${{ secrets.SERVER_SRC_PATH }}
          destination-path: ${{ secrets.SERVER_DEST_PATH }}
