name: deploy
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy'
        default: 'env'
        required: true
        type: choice
        options:
          - 'env'
          - 'sftp'
          - 'ftps'
jobs:
  bulid:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Unity Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.4f1

      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/WebGL/WebGL

      - name: Deploy by SFTP
        if: ${{ inputs.deploy == 'sftp' || inputs.deploy == 'env' && vars.DEPLOY_PROTOCOL == 'sftp' }}
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SERVER_HOST }}
          remote-user: ${{ secrets.SERVER_USER }}
          private-ssh-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-port: ${{ secrets.SERVER_PORT }}
          source-path: build/WebGL/WebGL/
          destination-path: ${{ secrets.SERVER_DEST_PATH }}
